CREATE DATABASE SCH;
USE SCH;
CREATE TABLE STD (
    RollNo INT PRIMARY KEY,
    Name VARCHAR(50),
    Marks INT,
    Grade CHAR(1)
);
SELECT * FROM STD;
ALTER TABLE STD
ADD contact VARCHAR(15);
SELECT * FROM STD;
ALTER TABLE STD
DROP COLUMN Grade;
SELECT * FROM STD;
ALTER TABLE STD
RENAME TO CLASSTEN;
SELECT * FROM CLASSTEN;
DELETE FROM CLASSTEN;
SELECT * FROM CLASSTEN;
DROP TABLE CLASSTEN;
SELECT * FROM CLASSTEN;
